### ISSUE TITLE
Crop by default is an annoying extra step

### ISSUE THREAD

**Issue by CubeOfCheese** [pixelfed/pixelfed-rn#27]
![Screenshot_20240626_205207_pixelfed](https://github.com/pixelfed/pixelfed-rn/assets/16740469/115d00e0-3617-495e-bb1f-1ab070f2af6e)
On the new post from gallery page, it positions the edges of the frame so that it would crop the image by default. I usually don't want to crop my pictures because I already carefully composed them. 

Also, it's weird that crop is a mandatory button to press. The first time I tried to hit the back button because I didn't want to crop it. "Continue" or something else would make more sense

**Comment by CubeOfCheese** [comment]
I see now there that there is a setting to disable the crop feature entirely. I don't think this is the best solution though because I will probably want to crop some pictures. 

I think going to the crop screen by default makes sense, but don't have it arbitrarily cropped by default. Go to the screen, but have the frame at the edges of the picture so that hitting "Continue" leaves the picture as it is.

**Comment by earth-walker** [comment]
I agree that cropping images by default is a suboptimal experience, especially because it can be hard to be sure that you have dragged the crop borders out all the way to the edges of the image.

Another possible workflow would be to skip the crop screen by default, but have it available to activate when you press the "options" button below the image preview on the post compose screen. (Along with the add alt text function)
