### ISSUE TITLE
Video thumbnails are blank on profiles

### ISSUE THREAD

**Issue by azuredusk10** [pixelfed/pixelfed-rn#30]
On the profile view, video posts have a blank square for a thumbnail in the post grid: 
![IMG_9140](https://github.com/pixelfed/pixelfed-rn/assets/18142893/ce550b03-f45f-4b2d-b9aa-129e1ea9f2c7)

App version 1.0.0 (48)
iOS 17.5.1 
iPhone 11

**Comment by dansup** [comment]
![IMG_5553](https://github.com/pixelfed/pixelfed-rn/assets/877217/5d272ac1-0d27-42d6-a899-0c12e745a1fe)
This is strange, because they are loading for me fine. Can you tap on a post, then tap on your avatar so your username is centered at the top (thats the non tab profile view) and see if the thumbs appear?

**Comment by dansup** [comment]
Going to close this for now, feel free to ping me if you are still experiencing this!

**Comment by azuredusk10** [comment]
Ahh I see the issue then. I am on the "Profile" tab. It only seems to appear when I'm viewing my own profile. When I'm viewing other people' profiles the video thumbnails work fine

**Comment by azuredusk10** [comment]
Not sure how to reopen the issue so I'll tag you @dansup in case my above comment gets lost. Thanks!

**Comment by Morse6690** [comment]
Yep, still getting the same problem when viewing my own profile. Viewing others is fine.
